#!/usr/bin/env bash

prj_file="${1}.prj"
tb_module="${1}_tb"
tcl_file="${tb_module}.tcl"
snapshot="${tb_module}_behav"
lib="xil_defaultlib"
wcfg="${snapshot}.wcfg"

xsim -g $snapshot -view $wcfg

rm *.pb
rm *.jou
rm *.log
